"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 04:00:10.932214
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("incident_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("trace", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_runs_incident_id"), ["incident_id"], unique=False
        )

    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("step_id", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approvals_incident_id"), ["incident_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_approvals_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_approvals_status"), ["status"], unique=False)

    op.create_table(
        "incident_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("incident_id", sa.String(length=32), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("incident_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_incident_events_incident_id"), ["incident_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_incident_events_ts"), ["ts"], unique=False)

    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("service", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("actions", sa.JSON(), nullable=False),
        sa.Column("alert_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incidents_service"), ["service"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_status"), ["status"], unique=False)

    op.create_table(
        "kanban_cards",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("board_id", sa.String(length=64), nullable=False),
        sa.Column("column", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("kanban_cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kanban_cards_board_id"), ["board_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_kanban_cards_column"), ["column"], unique=False)

    op.create_table(
        "knowledge_docs",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ops_events",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("service", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ops_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ops_events_service"), ["service"], unique=False)
        batch_op.create_index(batch_op.f("ix_ops_events_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("workflow", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workflow_runs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_workflow"), ["workflow"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_runs_workflow"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_status"))

    op.drop_table("workflow_runs")
    with op.batch_alter_table("ops_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ops_events_timestamp"))
        batch_op.drop_index(batch_op.f("ix_ops_events_service"))

    op.drop_table("ops_events")
    op.drop_table("knowledge_docs")
    with op.batch_alter_table("kanban_cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kanban_cards_column"))
        batch_op.drop_index(batch_op.f("ix_kanban_cards_board_id"))

    op.drop_table("kanban_cards")
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incidents_status"))
        batch_op.drop_index(batch_op.f("ix_incidents_service"))

    op.drop_table("incidents")
    with op.batch_alter_table("incident_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incident_events_ts"))
        batch_op.drop_index(batch_op.f("ix_incident_events_incident_id"))

    op.drop_table("incident_events")
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approvals_status"))
        batch_op.drop_index(batch_op.f("ix_approvals_run_id"))
        batch_op.drop_index(batch_op.f("ix_approvals_incident_id"))

    op.drop_table("approvals")
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_runs_incident_id"))

    op.drop_table("agent_runs")
    # ### end Alembic commands ###
